/**
 * Paste only the exact profile-badge markup generated by LinkedIn's public
 * badge builder here. Do not add a second script tag: the contact component
 * loads LinkedIn's official loader once, and only when this value is present.
 *
 * Current integration state: LINKEDIN_BADGE_MARKUP_REQUIRED.
 */
export const officialLinkedInBadgeMarkup: string | null = null;

export const linkedInBadgeIntegrationState =
  officialLinkedInBadgeMarkup === null
    ? "LINKEDIN_BADGE_MARKUP_REQUIRED"
    : "OFFICIAL_MARKUP_CONFIGURED";
